exports:
  ./package.json: ./package.json
  .: ./src/index.ts
targets:
  - name: browser
    tsconfig: ./tsconfig.warp.browser.json
    resolveImports: true
  - name: react-native
    tsconfig: ./tsconfig.warp.react-native.json
    resolveImports: true
  - name: esm
    condition: import
    tsconfig: ./tsconfig.warp.esm.json
    resolveImports: true
  - name: commonjs
    condition: require
    tsconfig: ./tsconfig.warp.cjs.json
    resolveImports: true
