exports:
  ./package.json: ./package.json
  .: ./src/index.ts
targets:
  - name: workerd
    tsconfig: ../../../tsconfig.src.workerd.json
    resolveImports: true
  - name: browser
    tsconfig: ../../../tsconfig.src.browser.json
    resolveImports: true
  - name: esm
    condition: import
    tsconfig: ../../../tsconfig.src.esm.json
    resolveImports: true
  - name: commonjs
    condition: require
    tsconfig: ../../../tsconfig.src.cjs.json
    resolveImports: true
