exports:
  ./package.json: ./package.json
  .: ./src/index.ts
targets:
  - name: browser
    tsconfig: ./src/tsconfig.browser.json
    resolveImports: true
  - name: react-native
    tsconfig: ./src/tsconfig.react-native.json
    resolveImports: true
  - name: esm
    condition: import
    tsconfig: ../../../tsconfig.src.esm.json
    resolveImports: true
  - name: commonjs
    condition: require
    tsconfig: ../../../tsconfig.src.cjs.json
    resolveImports: true
